version: '3'

services:
  frontend:
    container_name: vite_ssr
    build: 
      context: ./
      dockerfile: Dockerfile
    # user: 1000:1000
    command: node server.js
    ports:
      - 5173:5173

